import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { StoryIR } from './ir';
import { CharacterId } from '../characters';

const HEADER =
    '// AUTO-GENERATED by @aquila/stories compiler. Do not edit by hand.\n\n';

function q(s: string): string {
    return JSON.stringify(s);
}

function emitSceneFile(story: StoryIR, sceneId: string): string {
    const scene = story.scenes.find(s => s.id === sceneId)!;
    const lines = scene.entries
        .map(
            e =>
                `    { characterId: CharacterId.${charKey(e.characterId)}, character: ${q(e.displayName)}, dialogue: ${q(e.dialogue)} },`
        )
        .join('\n');
    return (
        HEADER +
        `import type { DialogueEntry } from '../../../types';\n` +
        `import { CharacterId } from '../../../characters';\n\n` +
        `export const scene: DialogueEntry[] = [\n${lines}\n];\n`
    );
}

// Map the CharacterId *value* (e.g. 'li_jie') back to its enum *key* (e.g. 'LiJie').
const VALUE_TO_KEY: Record<string, string> = Object.fromEntries(
    Object.entries(CharacterId).map(([k, v]) => [v as string, k])
);
function charKey(value: string): string {
    const key = VALUE_TO_KEY[value];
    if (!key)
        throw new Error(`[story-compiler] no CharacterId key for "${value}"`);
    return key;
}

function emitDialogueIndex(story: StoryIR): string {
    const imports = story.scenes
        .map(s => `import { scene as s_${s.id} } from './scenes/${s.id}';`)
        .join('\n');
    const entries = story.scenes
        .map(s => `    ${q(s.id)}: s_${s.id},`)
        .join('\n');
    return (
        HEADER +
        `import type { DialogueMap } from '../../types';\n${imports}\n\n` +
        `export const ${story.name}ZhDialogue: DialogueMap = {\n${entries}\n};\n`
    );
}

function emitFlow(story: StoryIR): string {
    const sceneNodes = story.scenes.map(s => {
        const next = s.next === null ? 'null' : q(s.next);
        return `    { kind: 'scene', id: ${q(s.id)}, sceneId: ${q(s.id)}, next: ${next} },`;
    });
    const choiceNodes = story.choices.map(c => {
        const opts = c.options
            .map(o => `${q(o.optionId)}: ${q(o.nextScene)}`)
            .join(', ');
        return `    { kind: 'choice', id: ${q('choice:' + c.choiceId)}, choiceId: ${q(c.choiceId)}, nextByOption: { ${opts} } },`;
    });
    const union =
        story.scenes.map(s => `    | ${q(s.id)}`).join('\n') || '    | never';
    return (
        HEADER +
        `import type { FlowConfig } from '../../flow-types';\n\n` +
        `export type ${cap(story.name)}SceneId =\n${union};\n\n` +
        `export const ${story.name}Flow: FlowConfig<${cap(story.name)}SceneId> = {\n` +
        `  start: ${q(story.start)},\n  nodes: [\n${[...sceneNodes, ...choiceNodes].join('\n')}\n  ],\n};\n`
    );
}

function emitChoiceTodo(story: StoryIR): string {
    const entries = story.choices
        .map(c => {
            const labels = c.options
                .map(o => `      ${q(o.optionId)}: 'TODO: ${o.optionId}',`)
                .join('\n');
            return `  ${q(c.choiceId)}: {\n    prompt: 'TODO: prompt for ${c.choiceId}',\n    labels: {\n${labels}\n    },\n  },`;
        })
        .join('\n');
    return (
        HEADER +
        `import type { ChoiceText } from '../../stories/choice-utils';\n\n` +
        `// Reference stub. Copy entries you need into choices.zh.ts and fill in real text.\n` +
        `export const ${story.name}ChoiceTextStub: ChoiceText = {\n${entries}\n};\n`
    );
}

function cap(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

export function emitStory(story: StoryIR, outDir: string): void {
    if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
    mkdirSync(join(outDir, 'scenes'), { recursive: true });
    for (const scene of story.scenes) {
        writeFileSync(
            join(outDir, 'scenes', `${scene.id}.ts`),
            emitSceneFile(story, scene.id)
        );
    }
    writeFileSync(join(outDir, 'dialogue.zh.ts'), emitDialogueIndex(story));
    writeFileSync(join(outDir, 'flow.ts'), emitFlow(story));
    writeFileSync(join(outDir, 'choices.todo.zh.ts'), emitChoiceTodo(story));
}
