import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { StoryIR } from './ir';
import type { ParsedCharacterDirectory } from './parse-characters';

const HEADER =
    '// AUTO-GENERATED by @aquila/stories compiler. Do not edit by hand.\n\n';

function q(s: string): string {
    return JSON.stringify(s);
}

function charEnumKey(id: string): string {
    return id
        .split('_')
        .map(s => s.charAt(0).toUpperCase() + s.slice(1))
        .join('');
}

/**
 * charEnumKey collapses distinct IDs that differ only in underscore placement
 * or capitalization (e.g. `foo_bar` and `fooBar` both -> `FooBar`). Deriving a
 * TS enum with duplicate members produces uncompilable output that is hard to
 * diagnose, so detect collisions up front and fail with the offending IDs.
 */
function assertNoCharEnumKeyCollisions(ids: string[]): void {
    const keyToIds = new Map<string, string[]>();
    for (const id of ids) {
        const key = charEnumKey(id);
        const list = keyToIds.get(key);
        if (list) list.push(id);
        else keyToIds.set(key, [id]);
    }
    const collisions = [...keyToIds.values()].filter(list => list.length > 1);
    if (collisions.length > 0) {
        const details = collisions
            .map(list => {
                const key = charEnumKey(list[0]);
                return `enum key "${key}" <- IDs ${list
                    .map(i => `"${i}"`)
                    .join(', ')}`;
            })
            .join('; ');
        throw new Error(
            `[story-compiler] character ID collision after enum-key derivation: ${details}`
        );
    }
}

function emitSceneFile(
    story: StoryIR,
    sceneId: string,
    assetEnums: {
        portraits?: Map<string, string>;
        backgrounds?: Map<string, string>;
    }
): string {
    const scene = story.scenes.find(s => s.id === sceneId)!;
    const hasPortraits = !!assetEnums.portraits?.size;
    const hasBackgrounds = !!assetEnums.backgrounds?.size;
    const lines = scene.entries
        .map(e => {
            const parts = [
                `characterId: CharacterId.${charKey(e.characterId)}`,
                `character: ${q(e.displayName)}`,
                `dialogue: ${q(e.dialogue)}`,
            ];
            if (e.background) {
                if (
                    hasBackgrounds &&
                    assetEnums.backgrounds!.has(e.background)
                ) {
                    parts.push(
                        `background: Background.${assetEnums.backgrounds!.get(e.background)}`
                    );
                } else {
                    parts.push(`background: ${q(e.background)}`);
                }
            }
            if (e.portrait) {
                if (hasPortraits && assetEnums.portraits!.has(e.portrait)) {
                    parts.push(
                        `portrait: Portrait.${assetEnums.portraits!.get(e.portrait)}`
                    );
                } else {
                    parts.push(`portrait: ${q(e.portrait)}`);
                }
            }
            return `    { ${parts.join(', ')} },`;
        })
        .join('\n');
    const imports = [
        `import type { DialogueEntry } from '../../../types';`,
        `import { CharacterId } from '../characters';`,
    ];
    if (hasPortraits) imports.push(`import { Portrait } from '../portraits';`);
    if (hasBackgrounds)
        imports.push(`import { Background } from '../backgrounds';`);
    return (
        HEADER +
        imports.join('\n') +
        `\n\nexport const scene: DialogueEntry[] = [\n${lines}\n];\n`
    );
}

function charKey(value: string): string {
    return charEnumKey(value);
}

function emitDialogueIndex(story: StoryIR): string {
    const imports = story.scenes
        .map(s => `import { scene as s_${s.id} } from './scenes/${s.id}';`)
        .join('\n');
    const entries = story.scenes
        .map(s => `    ${q(s.id)}: s_${s.id},`)
        .join('\n');
    return (
        HEADER +
        `import type { DialogueMap } from '../../types';\n${imports}\n\n` +
        `export const ${story.name}ZhDialogue: DialogueMap = {\n${entries}\n};\n`
    );
}

function emitFlow(story: StoryIR): string {
    const sceneNodes = story.scenes.map(s => {
        const next = s.next === null ? 'null' : q(s.next);
        return `    { kind: 'scene', id: ${q(s.id)}, sceneId: ${q(s.id)}, next: ${next} },`;
    });
    const choiceNodes = story.choices.map(c => {
        const opts = c.options
            .map(o => `${q(o.optionId)}: ${q(o.nextScene)}`)
            .join(', ');
        return `    { kind: 'choice', id: ${q('choice:' + c.choiceId)}, choiceId: ${q(c.choiceId)}, nextByOption: { ${opts} } },`;
    });
    const union =
        story.scenes.map(s => `    | ${q(s.id)}`).join('\n') || '    | never';
    return (
        HEADER +
        `import type { FlowConfig } from '../../flow-types';\n\n` +
        `export type ${cap(story.name)}SceneId =\n${union};\n\n` +
        `export const ${story.name}Flow: FlowConfig<${cap(story.name)}SceneId> = {\n` +
        `  start: ${q(story.start)},\n  nodes: [\n${[...sceneNodes, ...choiceNodes].join('\n')}\n  ],\n};\n`
    );
}

function emitChoiceTodo(story: StoryIR): string {
    const entries = story.choices
        .map(c => {
            const labels = c.options
                .map(o => `      ${q(o.optionId)}: 'TODO: ${o.optionId}',`)
                .join('\n');
            return `  ${q(c.choiceId)}: {\n    prompt: 'TODO: prompt for ${c.choiceId}',\n    labels: {\n${labels}\n    },\n  },`;
        })
        .join('\n');
    return (
        HEADER +
        `import type { ChoiceText } from '../../stories/choice-utils';\n\n` +
        `// Reference stub. Copy entries you need into choices.zh.ts and fill in real text.\n` +
        `export const ${story.name}ChoiceTextStub: ChoiceText = {\n${entries}\n};\n`
    );
}

function cap(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
}

function portraitEnumKey(portraitKey: string): string {
    const slashIdx = portraitKey.indexOf('/');
    const charIdValue = portraitKey.slice(0, slashIdx);
    const expression = portraitKey.slice(slashIdx + 1);
    return `${charKey(charIdValue)}_${cap(expression)}`;
}

function buildPortraitEnum(story: StoryIR): Map<string, string> {
    const keys = new Set<string>();
    for (const scene of story.scenes) {
        for (const entry of scene.entries) {
            if (entry.portrait) keys.add(entry.portrait);
        }
    }
    const map = new Map<string, string>();
    for (const k of [...keys].sort()) map.set(k, portraitEnumKey(k));
    return map;
}

function emitPortraits(portraitEnum: Map<string, string>): string | null {
    if (portraitEnum.size === 0) return null;
    const entries = [...portraitEnum.entries()]
        .map(([key, enumKey]) => `    ${enumKey} = ${q(key)},`)
        .join('\n');
    return HEADER + `export enum Portrait {\n${entries}\n}\n`;
}

function backgroundEnumKey(bgKey: string): string {
    return bgKey
        .replace(/\//g, '_')
        .split('_')
        .filter(s => s.length > 0)
        .map(cap)
        .join('_');
}

function buildBackgroundEnum(story: StoryIR): Map<string, string> {
    const keys = new Set<string>();
    for (const scene of story.scenes) {
        for (const entry of scene.entries) {
            if (entry.background) keys.add(entry.background);
        }
    }
    const map = new Map<string, string>();
    for (const k of [...keys].sort()) map.set(k, backgroundEnumKey(k));
    return map;
}

function emitBackgrounds(bgEnum: Map<string, string>): string | null {
    if (bgEnum.size === 0) return null;
    const entries = [...bgEnum.entries()]
        .map(([key, enumKey]) => `    ${enumKey} = ${q(key)},`)
        .join('\n');
    return HEADER + `export enum Background {\n${entries}\n}\n`;
}

function emitCharacters(dir: ParsedCharacterDirectory): string {
    assertNoCharEnumKeyCollisions(dir.characters.map(c => c.id));

    const enumEntries = dir.characters
        .map(c => `    ${charEnumKey(c.id)} = ${q(c.id)},`)
        .join('\n');

    const tableEntries = dir.characters
        .map(c => {
            const aliases =
                c.aliases.length > 0
                    ? `, aliases: [${c.aliases.map(q).join(', ')}]`
                    : ', aliases: []';
            return `    [CharacterId.${charEnumKey(c.id)}]: { id: ${q(c.id)}, name: ${q(c.name)}${aliases} },`;
        })
        .join('\n');

    return (
        HEADER +
        `export enum CharacterId {\n${enumEntries}\n}\n\n` +
        `export interface CharacterInfo {\n` +
        `    id: string;\n` +
        `    name: string;\n` +
        `    aliases: string[];\n` +
        `}\n\n` +
        `export const characterTable: Record<string, CharacterInfo> = {\n${tableEntries}\n};\n\n` +
        `const nameToId = new Map<string, string>();\n` +
        `for (const c of Object.values(characterTable)) {\n` +
        `    nameToId.set(c.name, c.id);\n` +
        `    for (const a of c.aliases) nameToId.set(a, c.id);\n` +
        `}\n\n` +
        `export class CharacterDirectory {\n` +
        `    static getById(id: string): CharacterInfo | undefined {\n` +
        `        return characterTable[id];\n` +
        `    }\n\n` +
        `    static getIdByName(name: string): string | undefined {\n` +
        `        return nameToId.get(name);\n` +
        `    }\n\n` +
        `    static getAll(): CharacterInfo[] {\n` +
        `        return Object.values(characterTable);\n` +
        `    }\n}\n`
    );
}

function emitPresentation(dir: ParsedCharacterDirectory): string {
    const slotEntries = dir.characters
        .filter(character => character.portraitSlot !== undefined)
        .map(
            character =>
                `            ${q(character.id)}: ${q(character.portraitSlot!)},`
        )
        .join('\n');

    return (
        HEADER +
        `import type { StoryPresentationMetadata } from "../../types";\n\n` +
        `export const storyPresentation = {\n` +
        `    portrait: {\n` +
        `        activeLimit: 1,\n` +
        `        defaultSlot: "center",\n` +
        `        slotsByCharacterId: {\n${slotEntries}\n        },\n` +
        `    },\n` +
        `} as const satisfies StoryPresentationMetadata;\n`
    );
}

export function emitStory(
    story: StoryIR,
    outDir: string,
    characterDir: ParsedCharacterDirectory
): void {
    if (existsSync(outDir)) rmSync(outDir, { recursive: true, force: true });
    mkdirSync(join(outDir, 'scenes'), { recursive: true });

    // Generate characters.ts
    writeFileSync(join(outDir, 'characters.ts'), emitCharacters(characterDir));
    writeFileSync(
        join(outDir, 'presentation.ts'),
        emitPresentation(characterDir)
    );

    const portraitEnum = buildPortraitEnum(story);
    const portraitsCode = emitPortraits(portraitEnum);
    if (portraitsCode) {
        writeFileSync(join(outDir, 'portraits.ts'), portraitsCode);
    }

    const backgroundEnum = buildBackgroundEnum(story);
    const backgroundsCode = emitBackgrounds(backgroundEnum);
    if (backgroundsCode) {
        writeFileSync(join(outDir, 'backgrounds.ts'), backgroundsCode);
    }

    const assetEnums = {
        portraits: portraitEnum.size > 0 ? portraitEnum : undefined,
        backgrounds: backgroundEnum.size > 0 ? backgroundEnum : undefined,
    };

    for (const scene of story.scenes) {
        writeFileSync(
            join(outDir, 'scenes', `${scene.id}.ts`),
            emitSceneFile(story, scene.id, assetEnums)
        );
    }
    writeFileSync(join(outDir, 'dialogue.zh.ts'), emitDialogueIndex(story));
    writeFileSync(join(outDir, 'flow.ts'), emitFlow(story));
    writeFileSync(join(outDir, 'choices.todo.zh.ts'), emitChoiceTodo(story));
    if (story.assetManifest) {
        writeFileSync(
            join(outDir, 'image-assets.json'),
            JSON.stringify(story.assetManifest, null, 2) + '\n'
        );
    }
}
